import type {
  LearnCoursePack,
  LearnQuizQuestion,
  LearnTutorialPack,
} from '@alice-wallet/alice-content/src/learn-types';

import { learnPackUrl } from './packs-base';

// Packs are static JSON generated by scripts/build-planb-learn.mjs, fetched
// lazily like /core-embeddings. English is served from the app itself
// (same-origin, works in the browser and in the Tauri webview); the other
// languages come from the remote base, see packs-base.ts.
const cache = new Map<string, unknown>();

async function fetchJson<T>(url: string): Promise<T> {
  const cached = cache.get(url);
  if (cached) return cached as T;
  const response = await fetch(url);
  if (!response.ok) throw new Error(`Pack indisponible (${response.status}): ${url}`);
  const data = (await response.json()) as T;
  cache.set(url, data);
  return data;
}

export function fetchCoursePack(lang: string, code: string): Promise<LearnCoursePack> {
  return fetchJson<LearnCoursePack>(learnPackUrl(lang, `courses/${code}.json`));
}

export async function fetchQuizPack(lang: string, code: string): Promise<LearnQuizQuestion[]> {
  try {
    return await fetchJson<LearnQuizQuestion[]>(learnPackUrl(lang, `quizzes/${code}.json`));
  } catch {
    // Not every course ships a quiz; absence is not an error.
    return [];
  }
}

export function fetchTutorialPack(
  lang: string,
  category: string,
  slug: string,
): Promise<LearnTutorialPack> {
  return fetchJson<LearnTutorialPack>(learnPackUrl(lang, `tutorials/${category}/${slug}.json`));
}
